five:
	rm -f *.o
	rm -f *.so
	gcc -Wall -o  server5 server5.c
	gcc -Wall -o client5 client5.c

pos:
	rm -f *.o
	rm -f *.so
	gcc -Wall -lrt -o clientpos clientpos.c
	gcc -Wall -lrt -o  serverpos serverpos.c
